notifications:
  email: false

before_install:
  - nvm install 10

script:
  - npm install
  - npm run build
  - npx cap copy android
  - npx cap sync
  - cd android
  - ./gradlew build connectedCheck

matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - android-29
