notifications:
  email: false

before_install:
  - nvm install 10
  - yes | sdkmanager "platforms;android-28"

script:
  - npm install
  - npx cap sync android
  - cd android
  - ./gradlew build connectedCheck

matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - android-29
        licenses:
          - android-sdk-license-.+