before_install:
  - nvm install 10
  - yes | sdkmanager "platforms;android-28"

script:
  - npm install
  - npm run build
  - npx cap sync android
  - cd android
  - ./gradlew assemble

matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - android-29