before_install:
  - nvm install 10

script:
  - npm run build
  - npm cap copy android

matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - android-29
      before_script:
        - cd android
