notifications:
  email: false

before_install:
  - nvm install 10

script:
  - npm install
  - npm install @capacitor/core @capacitor/cli
  - npm run build
  - npm cap copy android
  - cd android

matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          - android-29
